excluded:
  - Pods
  - .git

disabled_rules:
  - trailing_whitespace
  - class_delegate_protocol
  - weak_delegate
  - todo
  - cyclomatic_complexity
  - function_body_length
  - generic_type_name
  - identifier_name
  - unused_optional_binding

opt_in_rules:
  - overridden_super_call
  - prohibited_super_call
  - explicit_init
  - operator_usage_whitespace

large_tuple: 4

warning_threshold: 1

line_length:
  warning: 180

function_parameter_count:
  warning: 10
  error: 15

file_length:
  warning: 500

type_body_length:
  warning: 400
  error: 450

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length: 1
  max_length: 65

type_name:
  min_length: 3
  max_length: 65
